### ISSUE TITLE
save changes not working properly

### ISSUE THREAD

**Issue by bhavy03** [solomonshalom/The-Abyss#28]
![Screenshot (588)](https://github.com/solomonshalom/The-Abyss/assets/99943536/e9f4f3a3-4987-4405-ae98-2e05dadbb596)

when i click on save changes , the save changes button doesn't work properly

![Screenshot (587)](https://github.com/solomonshalom/The-Abyss/assets/99943536/8189677d-2d6a-442f-87cd-94f06433a1a0)

**Comment by solomonshalom** [comment]
Shalom! @bhavy03,

Just check it out and there seems to be no problem, might be a client-side error 🤔 

I am not really able to figure out what could causing it but if could disable any blockers, that could work - not so sure but give it a shot!

God Bless! Mate
