### ISSUE TITLE
A small change

### ISSUE THREAD

**Issue by solomonshalom** [solomonshalom/The-Abyss#30]
Shalom! @jennifershinshin,

Got a tad bit of a request, if possible, could you change this (When users don't have any posts)-
![image](https://github.com/solomonshalom/The-Abyss/assets/71135230/c15d3870-994c-46ac-be34-720c95da128a)
to this (Even if users have no posts, could you please implement this):
![image](https://github.com/solomonshalom/The-Abyss/assets/71135230/da9d72c2-d89a-415d-a725-08eb0be43c9a)

ONLY if it's possible, if not, I understand!

P.S. I tried doing it myself but I quite failed at it 😭

**Comment by jennifershinshin** [comment]
Of course! I can change it later tonight if I remember (10 hours from now), or tomorrow morning.

**Comment by solomonshalom** [comment]
> Of course! I can change it later tonight if I remember (10 hours from now), or tomorrow morning.

Shalom! @jennifershinshin,

Thank You! I hope this will not disrupt anything you were planning on doing, rightt?

**Comment by jennifershinshin** [comment]
![Screenshot 2023-10-03 at 10 22 07 AM](https://github.com/solomonshalom/The-Abyss/assets/6511897/28129ad4-b5d5-4516-b998-2edaba5cd985)

So just to be sure, is this what you wanted? Like have the search bar and remove the write a post and guide me buttons?

**Comment by solomonshalom** [comment]
> ![Screenshot 2023-10-03 at 10 22 07 AM](https://user-images.githubusercontent.com/6511897/272347106-28129ad4-b5d5-4516-b998-2edaba5cd985.png)
> 
> So just to be sure, is this what you wanted? Like have the search bar and remove the write a post and guide me buttons?

Shalom! @jennifershinshin,

Yes! It looks great, thank you!

P.S. The `?` button is there as well, rightt?

**Comment by jennifershinshin** [comment]
Yes it's there 😄
Ok I will make a PR for this.

**Comment by solomonshalom** [comment]
> Yes it's there 😄 Ok I will make a PR for this.

Yay! I will also see what I can do w/ the hacktoberfest contributions (It's weird that hacktoberfest didn't show the PR, it was merged just a day after it started 🤔 - Though, I will try a fix and do let me know if that works!)

**Comment by solomonshalom** [comment]
Does it work now? I know it does take few minutes, so give it a few reloads but do let me know! 😄 @jennifershinshin

**Comment by jennifershinshin** [comment]
Yes it worked! I see it. Thank you!

**Comment by solomonshalom** [comment]
> Yes it worked! I see it. Thank you!

Yay! Well - Slay it!
