### ISSUE TITLE
Update tabs to be highlighted when you're on that page and also include all tabs on every page

### ISSUE THREAD

**Issue by jennifershinshin** [solomonshalom/The-Abyss#42]
Hi! I have a suggestion for enhancing the tabs on each page.

I noticed that when you're on a page, like Dashboard or Reading List, you can't really tell that you're on that page.
To solve that problem, I figured we can add "Dashboard" to the tab list when you're on the Dashboard page, and "Reading List" when you're on the reading page, and highlight that tab.

I also noticed that the Reading List page doesn't have the "Contact" button in the tabs. I think as a general rule, we should keep the tabs the same throughout all our pages, so that when you're navigating between pages, it will look nice and seamless.
(Also I know you mentioned you wanted to get rid of the Contact tab, so let me know if you want me to remove it as well)

Let me know your thoughts if we should implement this! I already have it done in my [branch](https://github.com/jennifershinshin/The-Abyss/tree/tabs) so you can see what it looks like yourself.

This is what it will look like:

### Old Dashboard page
![Screenshot 2023-10-10 at 9 06 33 PM](https://github.com/solomonshalom/The-Abyss/assets/6511897/70f8f012-b13d-4508-ac5c-8b11b44ca262)

### New Dashboard page
![Screenshot 2023-10-10 at 9 08 05 PM](https://github.com/solomonshalom/The-Abyss/assets/6511897/ef65c271-7412-4a85-9332-4364b3d2fff9)

### Old Reading List page
![Screenshot 2023-10-10 at 9 06 43 PM](https://github.com/solomonshalom/The-Abyss/assets/6511897/ad28fc39-36c6-43b2-8808-c03665bddea7)

### New Reading List page
![Screenshot 2023-10-10 at 9 08 12 PM](https://github.com/solomonshalom/The-Abyss/assets/6511897/c58179c6-d41f-4065-909b-440ff6c15369)

**Comment by solomonshalom** [comment]
> Hi! I have a suggestion for enhancing the tabs on each page.
> 
> I noticed that when you're on a page, like Dashboard or Reading List, you can't really tell that you're on that page. To solve that problem, I figured we can add "Dashboard" to the tab list when you're on the Dashboard page, and "Reading List" when you're on the reading page, and highlight that tab.
> 
> I also noticed that the Reading List page doesn't have the "Contact" button in the tabs. I think as a general rule, we should keep the tabs the same throughout all our pages, so that when you're navigating between pages, it will look nice and seamless. (Also I know you mentioned you wanted to get rid of the Contact tab, so let me know if you want me to remove it as well)
> 
> Let me know your thoughts if we should implement this! I already have it done in my [branch](https://github.com/jennifershinshin/The-Abyss/tree/tabs) so you can see what it looks like yourself.
> 
> This is what it will look like:
> 
> ### Old Dashboard page
> ![Screenshot 2023-10-10 at 9 06 33 PM](https://user-images.githubusercontent.com/6511897/274139272-70f8f012-b13d-4508-ac5c-8b11b44ca262.png)
> 
> ### New Dashboard page
> ![Screenshot 2023-10-10 at 9 08 05 PM](https://user-images.githubusercontent.com/6511897/274139186-ef65c271-7412-4a85-9332-4364b3d2fff9.png)
> 
> ### Old Reading List page
> ![Screenshot 2023-10-10 at 9 06 43 PM](https://user-images.githubusercontent.com/6511897/274139311-ad28fc39-36c6-43b2-8808-c03665bddea7.png)
> 
> ### New Reading List page
> ![Screenshot 2023-10-10 at 9 08 12 PM](https://user-images.githubusercontent.com/6511897/274139214-c58179c6-d41f-4065-909b-440ff6c15369.png)

Shalom! @jennifershinshin,

Ah! That looks really good, make a PR and I will make a merge! 😄  

P.S. Yep! Remove the `Contact` button. ALSO, tad bit of a concern but will it be responsive if we were to keep the tabs the same in all of the page's headers? Super curious!

**Comment by jennifershinshin** [comment]
What do you mean by if it will be responsive if we were to keep the tabs the same in all of the page's headers? I tried testing it by clicking the tabs when they're the same and it did reroute me to the Dashboard/Reading List page, so not sure if that answers your question

Also can you add the hacktoberfest and hacktoberfest-accepted labs to this? Not sure if that's required to get credit for it.

**Comment by solomonshalom** [comment]
> What do you mean by if it will be responsive if we were to keep the tabs the same in all of the page's headers? I tried testing it by clicking the tabs when they're the same and it did reroute me to the Dashboard/Reading List page, so not sure if that answers your question
> 
> Also can you add the hacktoberfest and hacktoberfest-accepted labs to this? Not sure if that's required to get credit for it.

Shalom! @jennifershinshin,

OH, I meant in a little different way - I wanted to know if it would be responsive if we had more than 4 tabs (Especially in IOS devices, it didn't seem quite responsive). Though, if that isn't a problem then I think this would be a great merge 😁 

P.S. I am not so sure but I will just add the `hacktoberfest` labels to make sure! 😄

**Comment by jennifershinshin** [comment]
I did try testing it with more than 4 tabs, but only on my computer not my iPhone, and it worked just fine. I guess if we're having problems with it, I can push a fix.

**Comment by solomonshalom** [comment]
> I did try testing it with more than 4 tabs, but only on my computer not my iPhone, and it worked just fine. I guess if we're having problems with it, I can push a fix.

Ah, well - I guess we wouldn't have that issue but lemme check it out, I will let you know :D

**Comment by jennifershinshin** [comment]
Closing this issue since we want to move in a different direction for the UI: (command-bar / hamburger menu)

**Comment by solomonshalom** [comment]
> Closing this issue since we want to move in a different direction for the UI: (command-bar / hamburger menu)

Ah! Alright! Super excited to see what you come up w/ @jennifershinshin :D
