### ISSUE TITLE
react-script-tag dependency issues

### ISSUE THREAD

**Issue by jennifershinshin** [solomonshalom/The-Abyss#6]
Hello!
Please delete if this is not applicable.

I found a dependency issue when I first cloned the repo and installed the packages. I got this error
(I used npm instead of yarn for reference...)
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Espresso@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-script-tag@1.1.2
npm ERR! node_modules/react-script-tag
npm ERR!   react-script-tag@"^1.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

I did some research and there seems to be a legacy issue with react-script-tag.
I found this solution to work for me. You have to run these commands in the terminal.
```
npm config set legacy-peer-deps true
npm i
```

I got this solution from this [StackOverflow issue](https://stackoverflow.com/questions/72596908/could-not-resolve-dependency-error-peer-react16-8-0-17-0-0-from-materia)

**Comment by solomonshalom** [comment]
Hi @jennifershinshin 

Hmm, weird - I did face a similar issue but I resolved it w/ `npm install --force` but if `npm config set legacy-peer-deps true` is a more of a permanent solution, I think I can merge it w/ the production branch. 

P.S. Thank you so much for letting me know! I didn't know we had a different solution 😅

**Comment by solomonshalom** [comment]
I have worked on the PR, it seems to work but just look at it and do tell me! @jennifershinshin 

P.S. Will be merging it within 48 hours :D

**Comment by jennifershinshin** [comment]
@solomonshalom 
Yay! I took a look and it looks perfect.
This is my first contribution to open source so I'm still kind of new to this, but I'm happy I could help! 😃

**Comment by solomonshalom** [comment]
> @solomonshalom Yay! I took a look and it looks perfect. This is my first contribution to open source so I'm still kind of new to this, but I'm happy I could help! 😃

Wohoo! Thank you & I am so glad that this project is your first open-source contribution :D

How about this? Why don't you add a comment because if I we're to push the code w/o your reference in it, it would only show my name which wouldn't be fair and honestly, it's all you 😅

**Comment by jennifershinshin** [comment]
Ok! Do you mean like just leave a comment on the PR?

**Comment by solomonshalom** [comment]
> Ok! Do you mean like just leave a comment on the PR?

Yes! More specifically, on the files itself :D

Once done, I will review it once more to see if everything's alright and merge it! Super excited 🥳

**Comment by jennifershinshin** [comment]
Ok I left a lil comment in the code! I think that's what you meant 😅

**Comment by solomonshalom** [comment]
Dw, I've been there too 😆

But, I have added your as part of the contributors by adding a `AUTHORS.md` because it really is a great honor for our team to have our very first contributor <3

Thank You! @jennifershinshin

**Comment by jennifershinshin** [comment]
I'm honored as well and thank you too 🥹🥳

**Comment by solomonshalom** [comment]
This was such a cool dev-journey (if that's a word 😆)! thank you! (I know am saying it again but I really do appreciate it!) :D <3
